### ISSUE TITLE
Can't build from released tarball

### ISSUE THREAD

**Issue by dstndstn** [davidsd/sdpb#44]
Hi,

I'm trying to build from the latest tagged release, so I downloaded the tarball from https://github.com/davidsd/sdpb/releases/tag/2.4.0 .  When I run the "waf" command to configure it, it fails looking for the git tag:

```
$ ./waf configure --elemental-dir=/cm/shared/apps/elemental/sdpb-fork/
Setting top to                           : /home/dlang/sdpb-build/sdpb-2.4.0
Setting out to                           : /home/dlang/sdpb-build/sdpb-2.4.0/build
Checking for 'g++' (C++ compiler)        : mpicxx
Checking C++ 14 flag                     : yes
Checking for Boost                       : yes
Checking for GMPXX                       : yes
Checking for MPFR                        : yes
Checking for Elemental                   : yes
Checking for libxml2                     : not found
Checking for 'libxml-2.0'                : yes
Checking for rapidjson                   : yes
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "/home/dlang/sdpb-build/sdpb-2.4.0/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/home/dlang/sdpb-build/sdpb-2.4.0/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Scripting.py", line 179, in run_commands
    ctx=run_command(cmd_name)
  File "/home/dlang/sdpb-build/sdpb-2.4.0/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Scripting.py", line 170, in run_command
    ctx.execute()
  File "/home/dlang/sdpb-build/sdpb-2.4.0/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/home/dlang/sdpb-build/sdpb-2.4.0/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Context.py", line 85, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/dlang/sdpb-build/sdpb-2.4.0/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/home/dlang/sdpb-build/sdpb-2.4.0/wscript", line 14, in configure
    conf.env.git_version=subprocess.check_output('git describe --dirty', universal_newlines=True, shell=True).rstrip()
  File "/cm/shared/apps/miniconda3/miniconda3-4.6.14/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/cm/shared/apps/miniconda3/miniconda3-4.6.14/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'git describe --dirty' returned non-zero exit status 128.
```

Clearly I will just try git cloning the repo and checking out the tag, but thought I would report this issue in case others come across it.  Thanks.

**Comment by wlandry** [comment]
Building from the tarball is not supported.  I have added a note to `Install.md` to clarify this.  Thanks.
